name: Continuous integration
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  repository_dispatch:
    types:
      - build_testing
      - build_stable

jobs:
  build:
    name: build release
    runs-on: windows-2022
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date_long::$(date +'%Y%m%d%H')"
      - name: Set version
        run: |
          sed -i'' "s/dev/${{ steps.vars.outputs.sha_short }}/" version.h
          sed -i'' "s/none/${{ steps.vars.outputs.date_long }}/" version.h
          echo '' >> version.h
          cat version.h
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build release
        run: |
          MSBuild.exe SrcdsGuardian.vcxproj -property:Configuration=Release
      - name: Store release
        uses: actions/upload-artifact@v2
        with:
          name: srcds-guardian
          path: |
            x64/Release/SrcdsGuardian.exe
            x64/Release/SrcdsGuardian.pdb
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          update_release_body: false
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            Release/SrcdsGuardian.exe
